### ISSUE TITLE
Notice: Undefined index: roles in app/class-view-settings.php

### ISSUE THREAD

**Issue by ikappas** [justintadlock/members-admin-access#2]
Hi Justin, 

And thank you for your members plugin.

I was trying the members admin access plugin an run into the following issue:

If you turn on php notices and update Admin Access Settings you will get:

Notice: Undefined index: roles in /path/to/project/wp-content/plugins/members-admin-access/app/class-view-settings.php

followed by a 

Warning: Cannot modify header information - headers already sent by ...

And an app stop.

This is an easy fix adding an isset like:
```php
if ( ! isset( $settings['roles'] ) )
    $settings['roles'] = array();
```

**Comment by justintadlock** [comment]
That would be a good check to add.

I'm curious how you got to the point of not having any roles in the array.  Do you not have an `administrator` role?  Or, have you filtered roles with permanent access?

**Comment by ikappas** [comment]
Thx for your swift response! 

I got that on a clean installation of WordPress 4.9.8 with only Members and Members Admin Access installed and activated.

Activated Members and configured with the following options:

**Roles and Capabilities**
[x] Enable the role manager. 
[ ] Allow users to be assigned more than a single role. 
[x] Denied capabilities should always overrule granted capabilities. 
[x] Show human-readable capabilities when possible.

**Content Permissions**
[x] Enable the content permissions feature. 
default error message

**Sidebar Widgets**
[ ] Enable the login form widget.
[ ] Enable the users widget. 

**Private Site**
[x] Redirect all logged-out users to the login page before allowing them to view the site. 
[x] Require authentication for access to the REST API. 
[x] Show error message for feed items. 
default feed error message

Activated Members - Admin Access and went to configure with
**Select Roles**
[x] Administrator (disabled)
[ ] Editor
[ ] Author
[ ] Contributor
[ ] Subscriber

**Redirect users without access to**
site url (default)

[x] Disable toolbar on the front end for users without admin access. 

Update Settings raises the notice.

**Comment by ikappas** [comment]
I assume that the issue  happens because the administrator role in members_admin_access_settings[roles][]  is disabled so it is not posted on submit.

**Comment by justintadlock** [comment]
Yep, I was just thinking about that.
